Out boarding
DevHeyamAwad/movies_app pull request #8
Opened 2023-05-28 00:56 UTC by DevHeyamAwad

2023-05-28 19:19 UTC, Muhanned-Anwar approved these changes

2023-06-05 14:16 UTC, asilnaji21 requested changes
A tip I learned recently...!!!
In Flutter, blank lines can affect the layout and spacing of widgets in the user interface. When you leave blank lines between strings of code, it can introduce extra spacing between widgets, especially if the code is within a Column, Row, or other layout widgets.
_____________________________________________________________________________________________________
*_*### I will give you a small example so that we know where the effect is, which few of us can notice**_
Column(
  children: [
    Text('ASIL'),
    
    Text('NAJI'),
  ],
)
In this case, the blank line between Text('ASIL') and Text('NAJI') introduces additional space between the two Text  in the column. This can impact the visual layout of your UI.
_____________________________________________________________________________________________________
It is generally recommended to remove unnecessary blank lines between UI elements in Flutter code. However, it should be noted that intentional spaces can be used for visual separation or to improve readability and this means that unnecessary spaces should be removed.

2023-06-05 19:31 UTC, ZainabH3 approved these changes

2023-06-13 09:37 UTC, mayadaabed approved these changes

2023-06-13 15:10 UTC, Muhanned-Anwar approved these changes

2023-06-13 18:15 UTC, merged